'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,CheckCheck,ChevronDown,LockKeyhole,Luggage,Minus,Plus,RotateCcw,Shirt,BriefcaseBusiness,Flower2,PackagePlus,StickyNote} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {DestinationPicker,DayWeather,useWeather,dateForDay} from './Weather';
import {initialState,makeItems,isPacked,patchTrip,validateState,migrateState,PURPOSES,TRANSPORTS,type Day,type PackingState,type Trip,type Item} from '@/lib/packing';

type SaveStatus='loading'|'saved'|'saving'|'error';
export default function Home(){
 const [state,setState]=useState<PackingState>(initialState),[status,setStatus]=useState<SaveStatus>('loading'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('all'),[customName,setCustomName]=useState(''),[dialog,setDialog]=useState<'reset'|'reload'|null>(null);
 const [openNotes,setOpenNotes]=useState<Record<string,boolean>>({});
 const stateRef=useRef(state),dirty=useRef(false),busy=useRef(false),ready=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const saveRef=useRef<()=>Promise<void>>(async()=>{});
 const items=makeItems(state), active=items.filter(i=>i.qty>0),done=active.filter(i=>isPacked(state,i)).length,business=state.trip.daily.filter(d=>d.work).length,privateCount=state.trip.daily.filter(d=>d.private).length,travelCount=state.trip.daily.filter(d=>d.travel).length;
 const weather=useWeather(state.trip);
 const loading=status==='loading',percent=active.length?Math.round(done/active.length*100):0;
 const STORAGE_KEY='travel-packing-checklist:v1';
 async function load(){setStatus('loading');setError('');ready.current=false;try{const raw=localStorage.getItem(STORAGE_KEY);const next=raw?migrateState(JSON.parse(raw)):initialState();stateRef.current=next;setState(next);dirty.current=false;ready.current=true;setStatus('saved');}catch(e){setError('保存内容を読み込めませんでした。ブラウザーの保存設定を確認してください');setStatus('error');}}
 async function save(){if(busy.current||!ready.current||!dirty.current)return;busy.current=true;setStatus('saving');setError('');try{localStorage.setItem(STORAGE_KEY,JSON.stringify(stateRef.current));dirty.current=false;setStatus('saved');}catch{setStatus('error');setError('このブラウザーに保存できませんでした。容量やプライベートブラウズの設定を確認し、画面を閉じずに再試行してください');}finally{busy.current=false;}}
 saveRef.current=save;
 function change(next:PackingState){if(!ready.current)return;validateState(next);stateRef.current=next;setState(next);dirty.current=true;setStatus('saving');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void saveRef.current(),350);}
 useEffect(()=>{void load();const warn=(e:BeforeUnloadEvent)=>{if(dirty.current||busy.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);if(timer.current)clearTimeout(timer.current);};},[]);
 function trip(patch:Partial<Trip>){try{change(patchTrip(stateRef.current,patch));setNotice('');}catch(e){setNotice(e instanceof Error?e.message:'条件を確認してください');}}
 function quantity(item:Item,qty:number){if(!Number.isInteger(qty)||qty<0||qty>99)return;change({...stateRef.current,overrides:{...stateRef.current.overrides,[item.id]:qty}});}
 function check(id:string,checked:boolean){const s=stateRef.current,i=makeItems(s).find(i=>i.id===id);if(!i||i.qty===0)return;change({...s,packed:{...s.packed,[id]:checked?i.qty:0}});}
 function note(id:string,value:string){const s=stateRef.current;change({...s,notes:{...s.notes,[id]:value}});}
 function addCustom(){const name=customName.trim();if(!name)return;if(stateRef.current.custom.length>=50){setNotice('追加の持ち物は50件までです');return;}change({...stateRef.current,custom:[...stateRef.current.custom,{id:`custom-${crypto.randomUUID()}`,name,qty:1}]});setCustomName('');setFilter('all');}
 const api=useRef({change,trip,check,save});api.current={change,trip,check,save};
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;
  const life=new AbortController();const tools=[{name:'get_packing_checklist',title:'持ち物を確認',description:'現在の条件、持ち物の数量、チェック状態を読む',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({trip:stateRef.current.trip,items:makeItems(stateRef.current).map(i=>({id:i.id,name:i.name,quantity:i.qty,packed:isPacked(stateRef.current,i),note:stateRef.current.notes?.[i.id]??''}))})},{name:'set_packing_checks',title:'荷物のチェックを更新',description:'指定した持ち物のチェックを更新して保存する',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string'},packed:{type:'boolean'}},required:['id','packed'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!ready.current)throw new Error('保存内容の読み込みが必要です');const v=input as {items:{id:string,packed:boolean}[]};if(!v||!Array.isArray(v.items)||v.items.length>100)throw new Error('itemsを確認してください');const s=stateRef.current,list=makeItems(s),packed={...s.packed};for(const a of v.items){const i=list.find(i=>i.id===a.id);if(!i||i.qty<1||typeof a.packed!=='boolean')throw new Error('持参する品目とチェック状態を指定してください');packed[a.id]=a.packed?i.qty:0;}api.current.change({...s,packed});await api.current.save();while(busy.current)await new Promise(r=>setTimeout(r,30));if(dirty.current)throw new Error('保存できませんでした');await new Promise(r=>requestAnimationFrame(()=>r(null)));return{updated:v.items.length};}}];
  for(const tool of tools)try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}
  return()=>life.abort();
 },[]);
 function itemRow(i:Item){const packed=isPacked(state,i),old=state.packed[i.id]??0;return <div className={`item ${packed?'is-packed':''} ${i.qty===0?'is-excluded':''}`} key={i.id}>
  {i.qty>0?<Checkbox id={`check-${i.id}`} className="packing-check" checked={packed} onCheckedChange={v=>check(i.id,v===true)} disabled={!ready.current} aria-label={`${i.name}を準備済みにする`}/>:<span className="excluded-icon"><Minus size={18}/></span>}
  <div className="item-copy"><label htmlFor={`check-${i.id}`} className="item-name">{i.name}</label>{i.reason&&<p>{i.reason}</p>}{old>0&&old<i.qty&&<p className="recheck">数量が増えました。再確認してください</p>}{state.overrides[i.id]!==undefined&&<button className="auto-link" onClick={()=>{const overrides={...state.overrides};delete overrides[i.id];change({...state,overrides});}}>自動計算に戻す</button>}</div>
  {i.qty>0?<div className="item-actions"><div className="quantity"><input aria-label={`${i.name}の数量`} type="number" inputMode="numeric" min="0" max="99" value={i.qty} onChange={e=>quantity(i,Number(e.target.value))}/><span>{i.unit}</span></div><button className="exclude-button" onClick={()=>quantity(i,0)}>不要</button></div>:<button className="restore-button" onClick={()=>quantity(i,Math.max(1,i.auto))}>持参する</button>}
  <div className="item-note-control"><button className={`note-toggle ${state.notes?.[i.id]?'has-note':''}`} aria-label={`${i.name}のメモ${openNotes[i.id]?'を閉じる':'を編集'}`} aria-expanded={!!openNotes[i.id]} aria-controls={`note-${i.id}`} onClick={()=>setOpenNotes(prev=>({...prev,[i.id]:!prev[i.id]}))}><StickyNote size={17}/><span>{state.notes?.[i.id]?'メモあり':'メモ'}</span></button></div>
  {openNotes[i.id]&&<div className="item-note-editor" id={`note-${i.id}`}><label htmlFor={`note-input-${i.id}`}>{i.name}のメモ</label><textarea id={`note-input-${i.id}`} maxLength={1000} rows={3} placeholder="例：必要な部数、入れる場所など" value={state.notes?.[i.id]??''} onChange={e=>note(i.id,e.target.value)}/><span>自動保存・1000文字まで</span></div>}
  {!openNotes[i.id]&&state.notes?.[i.id]&&<p className="item-note-preview">{state.notes[i.id]}</p>}
 </div>}
 return <main className="app"><header className="app-header"><div className="brand-icon"><Luggage size={25}/></div><h1>出張の持ち物</h1><span className="private-badge"><LockKeyhole size={13}/>端末内に保存</span></header>
 <div className="workspace"><aside className="setup"><section className="panel trip-panel"><div className="section-heading"><h2>今回の予定</h2><span className="trip-summary">{state.trip.days===1?'日帰り':`${state.trip.days-1}泊${state.trip.days}日`}</span></div>
 <div className="trip-title-field"><label htmlFor="trip-title">出張タイトル</label><input id="trip-title" maxLength={100} placeholder="例：東京出張・秋の研修" value={state.trip.title??''} disabled={!ready.current} onChange={e=>trip({title:e.target.value})}/></div>
 <div className="day-grid"><div><label htmlFor="trip-days">全日数</label><div className="stepper"><button aria-label="全日数を減らす" disabled={loading||state.trip.days===1} onClick={()=>trip({days:state.trip.days-1})}><Minus size={17}/></button><input id="trip-days" type="number" inputMode="numeric" min="1" max="30" value={state.trip.days} disabled={loading} onChange={e=>trip({days:Number(e.target.value)})}/><span>日</span><button aria-label="全日数を増やす" disabled={loading||state.trip.days===30} onClick={()=>trip({days:state.trip.days+1})}><Plus size={17}/></button></div></div>
 </div>
 <div className="date-destination"><label htmlFor="start-date">出発日</label><input id="start-date" type="date" value={state.trip.startDate??''} onChange={e=>{if(e.target.value){trip({startDate:e.target.value});setNotice('日程を変更しました。チケットの日付も確認してください');}}}/><DestinationPicker label="主な行き先" city={state.trip.city??null} onSelect={city=>trip({city})}/></div>
 <div className="daily-editor"><p className="daily-heading">日ごとの目的 <span>複数選択できます</span></p>{state.trip.daily.map((day,index)=><div className="day-card" key={index}><div className="daily-row"><strong>{index+1}<span>日目</span><small>{state.trip.startDate?dateForDay(state.trip.startDate,index).slice(5).replace('-','/'):'日付未設定'}</small></strong><div>{([['work','仕事'],['travel','移動'],['private','私用']] as const).map(([key,label])=><label key={key} className={`day-purpose ${day[key]?'selected':''}`}><Checkbox disabled={loading} checked={day[key]} onCheckedChange={v=>{const daily=state.trip.daily.map((d,i)=>i===index?{...d,[key]:v===true}:d);trip({daily});}}/><span>{label}</span></label>)}</div></div><DayWeather trip={state.trip} day={day} index={index} weather={weather}/><details className="day-details"><summary>{day.travel?'移動手段・この日の行き先':'この日の行き先を変える'}</summary>{day.travel&&<div className="transport-options">{TRANSPORTS.map(mode=><label key={mode.id}><Checkbox checked={(day.transports??[]).includes(mode.id)} onCheckedChange={v=>{const transports=v?[...(day.transports??[]),mode.id]:(day.transports??[]).filter(id=>id!==mode.id);trip({daily:state.trip.daily.map((d,i)=>i===index?{...d,transports}:d)});}}/>{mode.label}</label>)}</div>}<DestinationPicker label={`${index+1}日目の行き先（未設定なら主な行き先）`} city={day.city??null} onSelect={city=>trip({daily:state.trip.daily.map((d,i)=>i===index?{...d,city}:d)})}/></details></div>)}</div>
 <p className="small-help">仕事 {business}日・移動 {travelCount}日・プライベート {privateCount}日<br/>同じ日に複数の目的があっても、下着は1日分です</p>
 <div className="weather-credit"><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">天気: Open-Meteo</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a><br/><a href="https://www.geonames.org/" target="_blank" rel="noreferrer">地名: GeoNames</a> · 天気の表記を日本語に変換<br/>日付は行き先の現地日付。予報は今日を含む最大16日分<br/><button onClick={weather.refresh}>天気を更新</button></div>
 <div className="purpose-heading">仕事の目的 <span>複数選択</span></div><div className="purpose-grid">{PURPOSES.map(p=><label key={p.id} className={`purpose ${state.trip.purposes.includes(p.id)&&business>0?'selected':''} ${business===0?'disabled':''}`}><Checkbox disabled={loading||business===0} checked={business>0&&state.trip.purposes.includes(p.id)} onCheckedChange={v=>trip({purposes:v?[...state.trip.purposes,p.id]:state.trip.purposes.filter(id=>id!==p.id)})}/>{p.label}</label>)}</div>{business===0&&<p className="small-help">仕事のない日程です。PCは初期設定では含めません</p>}
 <details className="options"><summary>服装・持ち物の条件<ChevronDown size={16}/></summary><div className="options-body"><p className="field-label">出発日の服装</p><RadioGroup value={!state.trip.daily[0].work?'private':!state.trip.daily[0].private?'business':state.trip.departure} onValueChange={v=>trip({departure:v as Trip['departure']})} className="departure-options">{[['business','仕事用'],['private','私服']].map(([v,l])=><label key={v}><RadioGroupItem value={v} disabled={loading||(v==='business'?!state.trip.daily[0].work:!state.trip.daily[0].private&&state.trip.daily[0].work)}/>{l}</label>)}</RadioGroup><label className="toggle-row"><span>下着・靴下・肌着を予備1つずつ</span><Switch checked={state.trip.spare} onCheckedChange={v=>trip({spare:v})}/></label><label className="toggle-row"><span>PCを持参する</span><Switch checked={state.trip.pc??business>0} onCheckedChange={v=>trip({pc:v})}/></label>{state.trip.pc!==null&&<button className="auto-link" onClick={()=>trip({pc:null})}>PCの判断を日程に合わせる</button>}<label className="toggle-row"><span>アメニティの充電器も持参</span><Switch checked={state.trip.chargers} onCheckedChange={v=>trip({chargers:v})}/></label></div></details>
 {notice&&<p role="alert" className="notice">{notice}</p>}</section>
 <section className="calculation-note"><Shirt size={19}/><div><strong>着ていく1日分は荷物に含めません</strong><p>下着・靴下・肌着は毎日交換、洗濯なしで計算。仕事用の上下や靴は着回す想定です。数量は自由に変えられます</p><details><summary>着ていく服装を確認</summary><ul>{items.filter(i=>i.worn>0).map(i=><li key={i.id}>{i.name}<span>{i.worn}{i.unit}</span></li>)}</ul></details></div></section></aside>
 <section className="packing-area"><div className="progress-panel"><div><p className="eyebrow">{state.trip.title||'荷造りチェック'}</p><h2>{active.length>0&&done===active.length?'準備できました':<>あと <strong>{active.length-done}</strong> 項目</>}</h2></div><div className="progress-number">{done}<span> / {active.length}</span></div><Progress value={percent} aria-label="荷造りの進み具合" className="packing-progress"/><p className="progress-caption">{percent===100?'出発前に、手元に残す物も確認しましょう':'バッグに入れたらチェック'}</p></div>
 <div className="save-status" role="status"><span>{status==='loading'?'保存内容を読み込み中…':status==='saving'?'保存中…':status==='saved'?<><Check size={13}/>このブラウザーに保存済み</>:'保存を確認してください'}</span></div>
 {error&&<div className="error-banner" role="alert"><p>{error}</p><div><button onClick={()=>ready.current?void save():void load()}>再試行</button>{ready.current&&<button onClick={()=>setDialog('reload')}>最新の保存内容に戻す</button>}</div></div>}
 <fieldset disabled={!ready.current} className="checklist-fieldset"><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs" aria-label="持ち物の表示"><TabsTrigger value="all">持参する</TabsTrigger><TabsTrigger value="todo">未チェック</TabsTrigger><TabsTrigger value="excluded">不要・対象外</TabsTrigger></TabsList></Tabs>
 <div className="item-groups">{['移動・チケット','衣類','仕事・電源','アメニティ','自分で追加'].map(cat=>{const rows=items.filter(i=>i.category===cat&&(filter==='excluded'?i.qty===0:i.qty>0&&(filter!=='todo'||!isPacked(state,i))));if(!rows.length)return null;const Icon=cat==='衣類'?Shirt:cat==='仕事・電源'?BriefcaseBusiness:cat==='アメニティ'?Flower2:PackagePlus;return <section className="item-group" key={cat}><h3><Icon size={17}/>{cat}<span>{rows.length}</span></h3>{rows.map(itemRow)}</section>})}{!items.some(i=>filter==='excluded'?i.qty===0:i.qty>0&&(filter!=='todo'||!isPacked(state,i)))&&<div className="empty"><CheckCheck size={30}/><p>{filter==='todo'?'すべてチェック済みです':'この表示の持ち物はありません'}</p></div>}</div>
 <form className="custom-form" onSubmit={e=>{e.preventDefault();addCustom();}}><label htmlFor="custom-name">持ち物を追加</label><div><input id="custom-name" maxLength={60} placeholder="例：折りたたみ傘" value={customName} onChange={e=>setCustomName(e.target.value)}/><button type="submit" disabled={!customName.trim()} aria-label="持ち物を追加"><Plus size={20}/><span>追加</span></button></div></form>
 <button className="reset-button" onClick={()=>setDialog('reset')}><RotateCcw size={15}/>チェックをやり直す</button></fieldset>
 <footer>タイトル・メモ・予定とチェックは、この端末・ブラウザー内にだけ保存されます<br/>別の端末には同期されません。サイトデータを消すとリストも消えます</footer></section></div>
 <AlertDialog open={dialog!==null} onOpenChange={open=>{if(!open)setDialog(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{dialog==='reset'?'チェックをすべて外しますか？':'最新の保存内容に戻しますか？'}</AlertDialogTitle><AlertDialogDescription>{dialog==='reset'?'タイトル・メモ・日程・数量・追加した持ち物は残ります。荷造りを最初から確認できます。':'この画面にある未保存の変更は失われます。保存されている最新のリストを読み込みます。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>キャンセル</AlertDialogCancel><AlertDialogAction onClick={()=>{if(dialog==='reset')change({...stateRef.current,packed:{}});else void load();setDialog(null);}}>{dialog==='reset'?'チェックを外す':'保存内容に戻す'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>;
}
