import {useEffect,useRef,useState} from 'react';
import {Search,MapPin} from 'lucide-react';
import type {City,Day,Trip} from '@/lib/packing';
export function dateForDay(start:string,index:number){const d=new Date(start+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+index);return d.toISOString().slice(0,10);}
const japaneseCities:Record<string,string>={'東京':'Tokyo','大阪':'Osaka','京都':'Kyoto','神戸':'Kobe','札幌':'Sapporo','横浜':'Yokohama','名古屋':'Nagoya','福岡':'Fukuoka','仙台':'Sendai','広島':'Hiroshima','那覇':'Naha','沖縄':'Okinawa','青森':'Aomori','盛岡':'Morioka','秋田':'Akita','山形':'Yamagata','福島':'Fukushima','水戸':'Mito','宇都宮':'Utsunomiya','前橋':'Maebashi','さいたま':'Saitama','埼玉':'Saitama','千葉':'Chiba','新潟':'Niigata','富山':'Toyama','金沢':'Kanazawa','福井':'Fukui','甲府':'Kofu','長野':'Nagano','岐阜':'Gifu','静岡':'Shizuoka','浜松':'Hamamatsu','津':'Tsu','大津':'Otsu','奈良':'Nara','和歌山':'Wakayama','鳥取':'Tottori','松江':'Matsue','岡山':'Okayama','山口':'Yamaguchi','徳島':'Tokushima','高松':'Takamatsu','松山':'Matsuyama','高知':'Kochi','佐賀':'Saga','長崎':'Nagasaki','熊本':'Kumamoto','大分':'Oita','宮崎':'Miyazaki','鹿児島':'Kagoshima','北九州':'Kitakyushu','川崎':'Kawasaki','堺':'Sakai','姫路':'Himeji','函館':'Hakodate','旭川':'Asahikawa','つくば':'Tsukuba'};
async function json(url:URL,signal?:AbortSignal){const r=await fetch(url,{signal:signal?AbortSignal.any([signal,AbortSignal.timeout(12000)]):AbortSignal.timeout(12000)});if(!r.ok)throw new Error('取得できませんでした。少し待って再試行してください');return r.json();}
export function DestinationPicker({label,city,onSelect}:{label:string;city:City|null;onSelect:(c:City|null)=>void}){
 const [query,setQuery]=useState(''),[results,setResults]=useState<City[]|null>(null),[pending,setPending]=useState(false),[error,setError]=useState('');const seq=useRef(0);
 async function search(){if(query.trim().length<2){setError('都市名を2文字以上で入力してください');return;}const request=++seq.current;setPending(true);setError('');setResults(null);try{const url=new URL('https://geocoding-api.open-meteo.com/v1/search');url.search=new URLSearchParams({name:query.trim(),count:'8',language:'ja',format:'json'}).toString();let data=await json(url);const alias=japaneseCities[query.trim()]??japaneseCities[query.trim().replace(/[都府県市]$/,'')];if(!(data.results?.length)&&alias){url.searchParams.set('name',alias);url.searchParams.set('countryCode','JP');data=await json(url);}if(request!==seq.current)return;const rows=(data.results??[]).map((r:{id:number,name:string,admin1?:string,country?:string,latitude:number,longitude:number,timezone?:string})=>({id:r.id,name:r.name,admin:r.admin1,country:r.country,lat:r.latitude,lon:r.longitude,timezone:r.timezone??'auto'}));setResults(rows);if(!rows.length)setError('都市が見つかりません。市名や英語名でもお試しください');}catch(e){if(request===seq.current)setError(e instanceof Error?e.message:'都市を検索できませんでした');}finally{if(request===seq.current)setPending(false);}}
 return <div className="destination-picker"><span className="field-label">{label}</span>{city&&<div className="selected-city"><MapPin size={14}/><span>{city.name}{city.admin&&city.admin!==city.name?`・${city.admin}`:''}</span><button type="button" onClick={()=>onSelect(null)}>解除</button></div>}<div className="city-search"><input aria-label={label+'の都市名'} placeholder="都市名（例：東京）" maxLength={100} value={query} onChange={e=>{seq.current++;setPending(false);setQuery(e.target.value);setResults(null);setError('');}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search();}}}/><button type="button" disabled={pending} aria-label={label+'の都市候補を検索'} onClick={()=>void search()}><Search size={18}/>{pending?'検索中':'検索'}</button></div>{results&&results.length>0&&<div className="city-results" aria-label="都市の候補">{results.map(c=><button type="button" key={c.id} onClick={()=>{onSelect(c);setResults(null);setQuery('');}}><strong>{c.name}</strong><span>{[c.admin,c.country].filter(Boolean).join('・')}</span></button>)}</div>}{error&&<p className="weather-error" role="alert">{error}</p>}</div>;
}
type Forecast={daily:{time:string[];temperature_2m_max:(number|null)[];temperature_2m_min:(number|null)[];precipitation_probability_max:(number|null)[];weather_code:(number|null)[]};timezone:string;fetchedAt:number};
type WeatherEntry={data?:Forecast;error?:string};
const cache=new Map<string,Forecast>();
const cityKey=(city:City)=>`${city.lat},${city.lon}`;
export function useWeather(trip:Trip){const [entries,setEntries]=useState<Record<string,WeatherEntry>>({}),[tick,setTick]=useState(0);const cities=Array.from(new Map(trip.daily.map(d=>d.city??trip.city).filter(Boolean).map(c=>[cityKey(c!),c!] as const)).values());const key=cities.map(cityKey).sort().join('|');
 useEffect(()=>{const controller=new AbortController();setEntries({});void Promise.all(cities.map(async city=>{const k=cityKey(city),existing=cache.get(k);if(existing&&Date.now()-existing.fetchedAt<30*60*1000){setEntries(e=>({...e,[k]:{data:existing}}));return;}try{const url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:String(city.lat),longitude:String(city.lon),daily:'temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code',timezone:'auto',forecast_days:'16',temperature_unit:'celsius'}).toString();const data=await json(url,controller.signal);if(!data.daily?.time)throw new Error('予報データがありません');const f={...data,fetchedAt:Date.now()} as Forecast;cache.set(k,f);if(!controller.signal.aborted)setEntries(e=>({...e,[k]:{data:f}}));}catch(e){if(!controller.signal.aborted)setEntries(prev=>({...prev,[k]:{error:e instanceof Error?e.message:'天気を取得できませんでした'}}));}}));return()=>controller.abort();},[key,tick]);
 return {entries,refresh:()=>{cache.clear();setTick(n=>n+1);}};
}
function condition(code:number|null|undefined){if(code==null)return '天気情報なし';if(code===0)return '晴れ';if(code===1)return 'おおむね晴れ';if(code===2)return '一部くもり';if(code===3)return 'くもり';if([45,48].includes(code))return '霧';if([51,53,55,56,57].includes(code))return '霧雨';if([61,63,65,66,67,80,81,82].includes(code))return '雨';if([71,73,75,77,85,86].includes(code))return '雪';if([95,96,97,99].includes(code))return '雷雨';return '天気情報なし';}
const temperature=(n:number|null|undefined)=>typeof n==='number'?Math.round(n)+'°':'—';
export function DayWeather({trip,day,index,weather}:{trip:Trip;day:Day;index:number;weather:ReturnType<typeof useWeather>}){const city=day.city??trip.city;if(!city)return null;const entry=weather.entries[cityKey(city)],date=trip.startDate?dateForDay(trip.startDate,index):null;if(!date)return <p className="daily-weather">予報を見るには出発日を入力してください</p>;if(!entry)return <p className="daily-weather">{city.name}：天気を取得中…</p>;if(entry.error)return <p className="daily-weather weather-error">{city.name}：天気を取得できません。「天気を更新」で再試行できます</p>;const f=entry.data!,idx=f.daily.time.indexOf(date);if(idx<0)return <p className="daily-weather">{city.name}：この日は予報の範囲外です</p>;const p=f.daily.precipitation_probability_max?.[idx];return <div className="daily-weather"><div><span>{city.name} · {condition(f.daily.weather_code?.[idx])}</span><strong>{temperature(f.daily.temperature_2m_max?.[idx])}<small> / {temperature(f.daily.temperature_2m_min?.[idx])}</small></strong></div><p>降水確率 {typeof p==='number'?`${p}%`:'情報なし'}<span>取得 {new Date(f.fetchedAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</span></p></div>}
